### ISSUE TITLE
not worked for me

### ISSUE THREAD

**Issue by fatemeh-farrahi** [persian-tools/persian-mobile-datepicker#3]
salam man package shoma ro nasb kardam faghat datepicker baz mishe vali ghabel taghir dadan date nist 
hata demo khode shoma ham vasam kar nemikone
 in version chrome man hast
Version 92.0.4515.131 (Official Build) (64-bit)

**Comment by fatemeh-farrahi** [comment]
I just did what you said in toturials

**Comment by fatemeh-farrahi** [comment]
I tested live demo too ,it didn't work for me

**Comment by ali-master** [comment]
I can't reproduce the issue that you have. Create a demo of what you did in codesandbox.

**Comment by ali-master** [comment]
> I tested live demo too ,it didn't work for me

May you record a video when you are scrolling inside this [demo](https://persian-tools.github.io/persian-mobile-datepicker/?path=/story/getting-started-dark-theme--dark-theme&args=theme:auto) and upload that here?

**Comment by fatemeh-farrahi** [comment]
Hello Dear,
I solve my problem
thank u

**Comment by ali-master** [comment]
What was that?

**Comment by fatemeh-farrahi** [comment]
hello Dear,
I have problem for jalali date , because I use toIsoDateSting() , it change
the selected date and I change it to toLocaleDateSting() and my problem
solved
فاطمه فرهی
