### ISSUE TITLE
@geometricpanda/storybook-addon-badges in dependencies

### ISSUE THREAD

**Issue by karianpour** [persian-tools/persian-mobile-datepicker#4]
Is it really necessary to have "@geometricpanda/storybook-addon-badges" in dependencies of the package?

When I install it, I have @geometricpanda/storybook-addon-badges in my package-lock file, which I believe is not necessary.

**Comment by ali-master** [comment]
Omg, your right. I'll fix it and release a new version today.

**Comment by ali-master** [comment]
v0.0.13 just released.
